# Generated by Django 4.1.6 on 2023-02-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('no_bedroom', models.IntegerField()),
                ('no_bathroom', models.IntegerField()),
                ('square_photage', models.IntegerField()),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
    ]
